version: "3.8"

services:
  backend:
    image: spring-boot-app
    build:
      context: ./backend/demo/demo
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/patient
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Abc123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect

  frontend:
    image: react-frontend
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://backend:8080
    depends_on:
      - backend

  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=patient
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Abc123456
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
