spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patient
    username: postgres
    password: Abc123456
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
server:
  port: 8081
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
