spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patient
    username: postgres
    password: Abc123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  flyway:
#    enabled: true
#    locations: classpath:db/migration

server:
  port: 8081

jwt:
  secret: mysecretkey
  expirationMs: 3600000

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
